- platform: template
  sensors:
    led_cucina_brightness_ok:
      entity_id: sensor.led_cucina_target_power, sensor.led_cucina_p
      value_template: "{{ (states('sensor.led_cucina_p')|float >= states('sensor.led_cucina_target_power')|float - states('input_number.epsilon')|float) and (states('sensor.led_cucina_p')|float <= states('sensor.led_cucina_target_power')|float + states('input_number.epsilon')|float) }}" 
    nice_weather:
      entity_id: wheater.home
      value_template: "{{ (states('weather.home') != 'lightning-rainy') and (states('weather.home') != 'pouring') and (states('weather.home') != 'rainy' and states('weather.home') != 'hail') }}"

- platform: template
  sensors:
    pump:
      value_template: "{{ is_state('switch.presa_balcone','on') }}"
      icon_template: "mdi:water-pump{{ '' if is_state('switch.presa_balcone','on') else '-off' }}"

- platform: template
  sensors:
    irrigation_freq_mode:
      value_template: "{{ is_state('input_boolean.irrigation_freq_minutes','on') }}"
      icon_template: "mdi:{{ 'alpha-m-circle-outline' if is_state('input_boolean.irrigation_freq_minutes','on') else 'alpha-h-circle-outline' }}"

- platform: template
  sensors:
    hvac_living_on:
      value_template: "{{ states('climate.hvac_living') != 'off' }}"
    hvac_bedroom_on:
      value_template: "{{ states('climate.hvac_bedroom') != 'off' }}"
    hvac_study_on:
      value_template: "{{ states('climate.hvac_study') != 'off' }}"
    hvac_tommy_on:
      value_template: "{{ states('climate.hvac_tommy') != 'off' }}"
    hvac_on:
      value_template: "{{ states('climate.hvac_living') != 'off' or states('climate.hvac_bedroom') != 'off' or states('climate.hvac_study') != 'off' or states('climate.hvac_tommy') != 'off' }}"
