
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include_dir_merge_list automations/
script: !include_dir_merge_named scripts/
scene: !include scenes.yaml
input_select: !include input_selects.yaml
input_text: !include input_text.yaml
sensor: !include_dir_merge_list sensors/
binary_sensor: !include binary_sensors.yaml
light: !include lights.yaml
cover: !include covers.yaml
switch: !include switches.yaml
recorder: !include recorder.yaml
logbook: !include logbook.yaml
utility_meter: !include utility_meters.yaml
input_number: !include input_numbers.yaml
input_boolean: !include input_booleans.yaml
zone: !include zones.yaml

logger:
  default: info

#http:
#  ssl_certificate: /ssl/fullchain.pem
#  ssl_key: /ssl/privkey.pem

api:

alexa:
  smart_home:

input_datetime:
  last_irrigation:
    has_date: true
    has_time: true

homekit:

mysql_list:
  host: !secret db_host
  database: dphouse
  user: !secret db_user
  password: !secret db_password
  table: music_bookmarks
  entity_id: input_select.music

#device_tracker:
#  - platform: nmap_tracker
#    hosts:
#      - 192.168.1.201
#      - 192.168.1.202
    #interval_seconds: 12 # seconds between each scan for new devices
    #consider_home: 330 # seconds to wait till marking someone as not home after not being seen
    #home_interval: 5 # minutes Nmap will not scan a device, assuming it is home
## interval_seconds = 12 implica che la presenza viene rivelata con al massimo 12 secondi di ritardo. 
## Dopo che la presenza è stata rivelata, le successive scansioni di quel device avvengono ogni 5
## minuti (home_interval = 5). Se viene rivelata l'assenza, tramite l'attesa del consider_home (5 min e 30 sec)
## si aspetta la successiva scansione (con periodo home_interval) prima di dichiarare il device away 
