
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include_dir_merge_list automations/
script: !include_dir_merge_named scripts/
scene: !include scenes.yaml
input_select: !include input_selects.yaml
input_text: !include input_text.yaml
sensor: !include_dir_merge_list sensors/
binary_sensor: !include binary_sensors.yaml
light: !include lights.yaml
cover: !include covers.yaml
switch: !include switches.yaml
recorder: !include recorder.yaml
logbook: !include logbook.yaml
utility_meter: !include utility_meters.yaml
input_number: !include input_numbers.yaml
zone: !include zones.yaml

logger:
  default: info

http:
  base_url: !secret domain
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

api:

alexa:
  smart_home:

input_boolean:
  dummy_switch:
  random_music:

homekit:
