- platform: mqtt
  name: "kitchen"
  command_topic: "shellies/shelly25-tapp_cucina/roller/0/command"
  position_topic: "shellies/shelly25-tapp_cucina/roller/0/pos"
  set_position_topic: "shellies/shelly25-tapp_cucina/roller/0/command/pos"
  # availability_topic: "shellies/shelly25-tapp_cucina/online"
  # payload_available: "true"
  # payload_not_available: "false"
  retain: false
  payload_open: "open"
  payload_close: "close"
  payload_stop: "stop"
  position_open: 100
  position_closed: 0
  optimistic: false
  qos: 0

- platform: mqtt
  name: "living_big"
  command_topic: "shellies/shelly25-tapp_sala_big/roller/0/command"
  position_topic: "shellies/shelly25-tapp_sala_big/roller/0/pos"
  set_position_topic: "shellies/shelly25-tapp_sala_big/roller/0/command/pos"
  # availability_topic: "shellies/shelly25-tapp_sala_big/online"
  # payload_available: "true"
  # payload_not_available: "false"
  retain: false
  payload_open: "open"
  payload_close: "close"
  payload_stop: "stop"
  position_open: 100
  position_closed: 0
  optimistic: false
  qos: 0

- platform: mqtt
  name: "living_small"
  command_topic: "shellies/shelly25-tapp_sala_small/roller/0/command"
  position_topic: "shellies/shelly25-tapp_sala_small/roller/0/pos"
  set_position_topic: "shellies/shelly25-tapp_sala_small/roller/0/command/pos"
  # availability_topic: "shellies/shelly25-tapp_sala_small/online"
  # payload_available: "true"
  # payload_not_available: "false"
  retain: false
  payload_open: "open"
  payload_close: "close"
  payload_stop: "stop"
  position_open: 100
  position_closed: 0
  optimistic: false
  qos: 0

- platform: mqtt
  name: "bedroom"
  command_topic: "shellies/shelly25-tapp_camera/roller/0/command"
  position_topic: "shellies/shelly25-tapp_camera/roller/0/pos"
  set_position_topic: "shellies/shelly25-tapp_camera/roller/0/command/pos"
  # availability_topic: "shellies/shelly25-tapp_camera/online"
  # payload_available: "true"
  # payload_not_available: "false"
  retain: false
  payload_open: "open"
  payload_close: "close"
  payload_stop: "stop"
  position_open: 100
  position_closed: 0
  optimistic: false
  qos: 0

- platform: mqtt
  name: "tommy"
  command_topic: "shellies/shelly25-tapp_Tommaso/roller/0/command"
  position_topic: "shellies/shelly25-tapp_Tommaso/roller/0/pos"
  set_position_topic: "shellies/shelly25-tapp_Tommaso/roller/0/command/pos"
  # availability_topic: "shellies/shelly25-tapp_Tommaso/online"
  # payload_available: "true"
  # payload_not_available: "false"
  retain: false
  payload_open: "open"
  payload_close: "close"
  payload_stop: "stop"
  position_open: 100
  position_closed: 0
  optimistic: false
  qos: 0

- platform: mqtt
  name: "study"
  command_topic: "shellies/shelly25-tapp_studio/roller/0/command"
  position_topic: "shellies/shelly25-tapp_studio/roller/0/pos"
  set_position_topic: "shellies/shelly25-tapp_studio/roller/0/command/pos"
  # availability_topic: "shellies/shelly25-tapp_studio/online"
  # payload_available: "true"
  # payload_not_available: "false"
  retain: false
  payload_open: "open"
  payload_close: "close"
  payload_stop: "stop"
  position_open: 100
  position_closed: 0
  optimistic: false
  qos: 0

- platform: mqtt
  name: "bathroom"
  command_topic: "shellies/shelly25-tapp_bagnetto/roller/0/command"
  position_topic: "shellies/shelly25-tapp_bagnetto/roller/0/pos"
  set_position_topic: "shellies/shelly25-tapp_bagnetto/roller/0/command/pos"
  # availability_topic: "shellies/shelly25-tapp_bagnetto/online"
  # payload_available: "true"
  # payload_not_available: "false"
  retain: false
  payload_open: "open"
  payload_close: "close"
  payload_stop: "stop"
  position_open: 100
  position_closed: 0
  optimistic: false
  qos: 0

- platform: group
  name: living
  entities:
    - cover.living_small
    - cover.living_big

- platform: group
  name: zona_giorno
  entities:
    - cover.kitchen
    - cover.living_small
    - cover.living_big

- platform: group
  name: zona_notte
  entities:
    - cover.bedroom
    - cover.study
    - cover.tommy
    - cover.bathroom

- platform: group
  name: all
  entities:
    - cover.kitchen
    - cover.living_small
    - cover.living_big
    - cover.bedroom
    - cover.study
    - cover.tommy
    - cover.bathroom
