# Shelly 1PM ingresso
- platform: mqtt
  name: "Ingresso"
  state_topic: "shellies/shelly1pm-ingresso/relay/0"
  command_topic: "shellies/shelly1pm-ingresso/relay/0/command"
  qos: 0
  payload_on: "on"
  payload_off: "off"
  retain: false

# Shelly 2.5 luci sala
- platform: mqtt
  name: "Flos Aim"
  state_topic: "shellies/shelly25-luci_sala/relay/0"
  command_topic: "shellies/shelly25-luci_sala/relay/0/command"
  qos: 0
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  retain: false
- platform: mqtt
  name: "led divano"
  state_topic: "shellies/shelly25-luci_sala/relay/1"
  command_topic: "shellies/shelly25-luci_sala/relay/1/command"
  qos: 0
  payload_on: "on"
  payload_off: "off"
  retain: false
# Shelly 1 Flos IC T2
- platform: mqtt
  name: "Flos IC T2"
  state_topic: "shellies/shelly1-ic_t2/relay/0"
  command_topic: "shellies/shelly1-ic_t2/relay/0/command"
  qos: 0
  payload_on: "on"
  payload_off: "off"
  retain: false

# Shelly 1 luce penisola
- platform: mqtt
  name: "Luce penisola"
  state_topic: "shellies/shelly1-penisola/relay/0"
  command_topic: "shellies/shelly1-penisola/relay/0/command"
  qos: 0
  payload_on: "on"
  payload_off: "off"
  retain: false

# Led cucina (luce virtuale)
- platform: template
  lights:
    led_cucina_virtual:
      friendly_name: "Led cucina"
      value_template: "{{ states('sensor.led_cucina_p') | float >= states('input_number.led_cucina_min_power') | float }}"
      turn_on:
        service: script.turn_on_led_cucina
      turn_off:
        service: script.turn_off_led_cucina

# Sonoff mini led sottopensili
- platform: mqtt
  name: "Led pensili"
  state_topic: "stat/tasmota-led_pensili/RESULT"
  value_template: "{{ value_json.POWER }}"
  command_topic: "cmnd/tasmota-led_pensili/POWER"
  availability_topic: "tele/tasmota-led_pensili/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false

# Sonoff mini camera
- platform: mqtt
  name: "Flos Ariette"
  state_topic: "stat/tasmota-camera/RESULT"
  value_template: "{{ value_json.POWER }}"
  command_topic: "cmnd/tasmota-camera/POWER"
  availability_topic: "tele/tasmota-camera/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false

# Sonoff mini Tommy
- platform: mqtt
  name: "Tommaso"
  state_topic: "stat/tasmota-tommy/RESULT"
  value_template: "{{ value_json.POWER }}"
  command_topic: "cmnd/tasmota-tommy/POWER"
  availability_topic: "tele/tasmota-tommy/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false

# Shelly 1 bagno
- platform: mqtt
  name: "Bagno"
  state_topic: "shellies/shelly1-bagno/relay/0"
  command_topic: "shellies/shelly1-bagno/relay/0/command"
  qos: 0
  payload_on: "on"
  payload_off: "off"
  retain: false

# Shelly 1 corridoio
- platform: mqtt
  name: "Corridoio"
  state_topic: "shellies/shelly1-corridoio/relay/0"
  command_topic: "shellies/shelly1-corridoio/relay/0/command"
  qos: 0
  payload_on: "on"
  payload_off: "off"
  retain: false
