# Shelly 2.5 luci sala
- platform: mqtt
  name: "Flos Aim"
  state_topic: "shellies/shelly25-luci_sala/relay/0"
  command_topic: "shellies/shelly25-luci_sala/relay/0/command"
  qos: 0
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  retain: false
- platform: mqtt
  name: "led divano"
  state_topic: "shellies/shelly25-luci_sala/relay/1"
  command_topic: "shellies/shelly25-luci_sala/relay/1/command"
  qos: 0
  payload_on: "on"
  payload_off: "off"
  retain: false
- platform: mqtt
  name: "Flos IC T2"
  state_topic: "shellies/shelly1-ic_t2/relay/0"
  command_topic: "shellies/shelly1-ic_t2/relay/0/command"
  qos: 0
  payload_on: "on"
  payload_off: "off"
  retain: false

# Shelly 2.5 luci cucina
# Il relay 0 è trattato come uno switch, non come una luce
#- platform: mqtt
#  name: "Led cucina"
#  state_topic: "shellies/shelly25-luci_cucina/relay/0"
#  command_topic: "shellies/shelly25-luci_cucina/relay/0/command"
#  qos: 0
#  payload_on: "on"
#  payload_off: "off"
#  optimistic: false
#  retain: false
- platform: mqtt
  name: "Luce penisola"
  state_topic: "shellies/shelly25-luci_cucina/relay/1"
  command_topic: "shellies/shelly25-luci_cucina/relay/1/command"
  qos: 0
  payload_on: "on"
  payload_off: "off"
  retain: false

- platform: template
  lights:
    led_cucina_virtual:
      friendly_name: "Led cucina"
      value_template: "{{ states('input_number.dummy_power') | float >= states('input_number.led_cucina_min_power') | float }}"
      turn_on:
        service: script.turn_on_led_cucina
      turn_off:
        service: script.turn_off_led_cucina
