- platform: mqtt
  name: "Flos Aim P"
  state_topic: "shellies/shelly25-luci_sala/relay/0/power"
  qos: 0
  unit_of_measurement: "W"
- platform: mqtt
  name: "Flos Aim E"
  state_topic: "shellies/shelly25-luci_sala/relay/0/energy"
  qos: 0
  unit_of_measurement: "Wh"
  value_template: "{{ (value|float / 60) | round(2) }}" # Fix for Watt-minutes
- platform: mqtt
  name: "Led divano P"
  state_topic: "shellies/shelly25-luci_sala/relay/1/power"
  qos: 0
  unit_of_measurement: "W"
- platform: mqtt
  name: "Led divano E"
  state_topic: "shellies/shelly25-luci_sala/relay/1/energy"
  qos: 0
  unit_of_measurement: "Wh"
  value_template: "{{ (value|float / 60) | round(2) }}" # Fix for Watt-minutes
- platform: mqtt
  name: "shelly25 luci sala T"
  state_topic: "shellies/shelly25-luci_sala/temperature"
  qos: 0
  unit_of_measurement: "°C"
- platform: mqtt
  name: "shelly25 luci sala Talarm"
  state_topic: "shellies/shelly25-luci_sala/overtemperature"
  qos: 0

- platform: mqtt
  name: "Led cucina P"
  state_topic: "shellies/shelly25-luci_cucina/relay/0/power"
  qos: 0
  unit_of_measurement: "W"
- platform: mqtt
  name: "Led cucina E"
  state_topic: "shellies/shelly25-luci_cucina/relay/0/energy"
  qos: 0
  unit_of_measurement: "Wh"
  value_template: "{{ (value|float / 60) | round(2) }}" # Fix for Watt-minutes
- platform: mqtt
  name: "Luce penisola P"
  state_topic: "shellies/shelly25-luci_cucina/relay/1/power"
  qos: 0
  unit_of_measurement: "W"
- platform: mqtt
  name: "Luce penisola E"
  state_topic: "shellies/shelly25-luci_cucina/relay/1/energy"
  qos: 0
  unit_of_measurement: "Wh"
  value_template: "{{ (value|float / 60) | round(2) }}" # Fix for Watt-minutes
- platform: mqtt
  name: "shelly25 luci cucina T"
  state_topic: "shellies/shelly25-luci_cucina/temperature"
  qos: 0
  unit_of_measurement: "°C"
- platform: mqtt
  name: "shelly25 luci cucina Talarm"
  state_topic: "shellies/shelly25-luci_cucina/overtemperature"
  qos: 0
