# Shelly 1PM ingresso
- platform: mqtt
  name: "Luce ingresso P"
  state_topic: "shellies/shelly1pm-ingresso/relay/0/power"
  qos: 0
  unit_of_measurement: "W"
- platform: mqtt
  name: "Luce ingresso E"
  state_topic: "shellies/shelly1pm-ingresso/relay/0/energy"
  qos: 0
  unit_of_measurement: "Wh"
  value_template: "{{ (value|float / 60) | round(2) }}" # Fix for Watt-minutes
- platform: mqtt
  name: "ingresso T"
  state_topic: "shellies/shelly1pm-ingresso/temperature"
  qos: 0
  unit_of_measurement: "°C"
- platform: mqtt
  name: "ingresso Talarm"
  state_topic: "shellies/shelly1pm-ingresso/overtemperature"
  qos: 0

# Shelly 2.5 luci sala
- platform: mqtt
  name: "Flos Aim P"
  state_topic: "shellies/shelly25-luci_sala/relay/0/power"
  qos: 0
  unit_of_measurement: "W"
- platform: mqtt
  name: "Flos Aim E"
  state_topic: "shellies/shelly25-luci_sala/relay/0/energy"
  qos: 0
  unit_of_measurement: "Wh"
  value_template: "{{ (value|float / 60) | round(2) }}" # Fix for Watt-minutes
- platform: mqtt
  name: "Led divano P"
  state_topic: "shellies/shelly25-luci_sala/relay/1/power"
  qos: 0
  unit_of_measurement: "W"
- platform: mqtt
  name: "Led divano E"
  state_topic: "shellies/shelly25-luci_sala/relay/1/energy"
  qos: 0
  unit_of_measurement: "Wh"
  value_template: "{{ (value|float / 60) | round(2) }}" # Fix for Watt-minutes
- platform: mqtt
  name: "luci sala T"
  state_topic: "shellies/shelly25-luci_sala/temperature"
  qos: 0
  unit_of_measurement: "°C"
- platform: mqtt
  name: "luci sala Talarm"
  state_topic: "shellies/shelly25-luci_sala/overtemperature"
  qos: 0

# Shelly 2.5 led cucina
# Il relay 0 non viene monitorato perché è usato come un pulsante
- platform: mqtt
  name: "Led cucina P"
  state_topic: "shellies/shelly25-luci_cucina/relay/1/power"
  qos: 0
  unit_of_measurement: "W"
- platform: mqtt
  name: "Led cucina E"
  state_topic: "shellies/shelly25-luci_cucina/relay/1/energy"
  qos: 0
  unit_of_measurement: "Wh"
  value_template: "{{ (value|float / 60) | round(2) }}" # Fix for Watt-minutes
- platform: mqtt
  name: "led cucina T"
  state_topic: "shellies/shelly25-luci_cucina/temperature"
  qos: 0
  unit_of_measurement: "°C"
- platform: mqtt
  name: "led cucina Talarm"
  state_topic: "shellies/shelly25-luci_cucina/overtemperature"
  qos: 0

# Shelly 2.5 luci studio
- platform: mqtt
  name: "Luce studio P"
  state_topic: "shellies/shelly25-luci_studio/relay/0/power"
  qos: 0
  unit_of_measurement: "W"
- platform: mqtt
  name: "Luce studio E"
  state_topic: "shellies/shelly25-luci_studio/relay/0/energy"
  qos: 0
  unit_of_measurement: "Wh"
  value_template: "{{ (value|float / 60) | round(2) }}" # Fix for Watt-minutes
- platform: mqtt
  name: "Faretti studio P"
  state_topic: "shellies/shelly25-luci_studio/relay/1/power"
  qos: 0
  unit_of_measurement: "W"
- platform: mqtt
  name: "Faretti studio E"
  state_topic: "shellies/shelly25-luci_studio/relay/1/energy"
  qos: 0
  unit_of_measurement: "Wh"
  value_template: "{{ (value|float / 60) | round(2) }}" # Fix for Watt-minutes
- platform: mqtt
  name: "luci studio T"
  state_topic: "shellies/shelly25-luci_studio/temperature"
  qos: 0
  unit_of_measurement: "°C"
- platform: mqtt
  name: "luci studio Talarm"
  state_topic: "shellies/shelly25-luci_studio/overtemperature"
  qos: 0

# Shelly 2.5 tapparella cucina
- platform: mqtt
  name: "kitchen_cover_P"
  state_topic: "shellies/shelly25-tapp_cucina/roller/0/power"
  qos: 0
  unit_of_measurement: "W"
- platform: mqtt
  name: "kitchen_cover_E"
  state_topic: "shellies/shelly25-tapp_cucina/roller/0/energy"
  qos: 0
  unit_of_measurement: "Wh"
  value_template: "{{ (value|float / 60) | round(2) }}" # Fix for Watt-minutes
- platform: mqtt
  name: "kitchen_cover_T"
  state_topic: "shellies/shelly25-tapp_cucina/temperature"
  qos: 0
  unit_of_measurement: "°C"
- platform: mqtt
  name: " kitchen_cover_Talarm"
  state_topic: "shellies/shelly25-tapp_cucina/overtemperature"
  qos: 0

# Shelly 2.5 tapparella sala balcone
- platform: mqtt
  name: "living_big_cover_P"
  state_topic: "shellies/shelly25-tapp_sala_big/roller/0/power"
  qos: 0
  unit_of_measurement: "W"
- platform: mqtt
  name: "living_big_cover_E"
  state_topic: "shellies/shelly25-tapp_sala_big/roller/0/energy"
  qos: 0
  unit_of_measurement: "Wh"
  value_template: "{{ (value|float / 60) | round(2) }}" # Fix for Watt-minutes
- platform: mqtt
  name: "living_big_cover_T"
  state_topic: "shellies/shelly25-tapp_sala_big/temperature"
  qos: 0
  unit_of_measurement: "°C"
- platform: mqtt
  name: "living_big_cover_Talarm"
  state_topic: "shellies/shelly25-tapp_sala_big/overtemperature"
  qos: 0

# Shelly 2.5 tapparella sala finestra
- platform: mqtt
  name: "living_small_cover_P"
  state_topic: "shellies/shelly25-tapp_sala_small/roller/0/power"
  qos: 0
  unit_of_measurement: "W"
- platform: mqtt
  name: "living_small_cover_E"
  state_topic: "shellies/shelly25-tapp_sala_small/roller/0/energy"
  qos: 0
  unit_of_measurement: "Wh"
  value_template: "{{ (value|float / 60) | round(2) }}" # Fix for Watt-minutes
- platform: mqtt
  name: "living_small_cover_T"
  state_topic: "shellies/shelly25-tapp_sala_small/temperature"
  qos: 0
  unit_of_measurement: "°C"
- platform: mqtt
  name: "living_small_cover_Talarm"
  state_topic: "shellies/shelly25-tapp_sala_small/overtemperature"
  qos: 0

# Shelly 2.5 tapparella camera
- platform: mqtt
  name: "bedroom_cover_P"
  state_topic: "shellies/shelly25-tapp_camera/roller/0/power"
  qos: 0
  unit_of_measurement: "W"
- platform: mqtt
  name: "bedroom_cover_E"
  state_topic: "shellies/shelly25-tapp_camera/roller/0/energy"
  qos: 0
  unit_of_measurement: "Wh"
  value_template: "{{ (value|float / 60) | round(2) }}" # Fix for Watt-minutes
- platform: mqtt
  name: "bedroom_cover_T"
  state_topic: "shellies/shelly25-tapp_camera/temperature"
  qos: 0
  unit_of_measurement: "°C"
- platform: mqtt
  name: "bedroom_cover_Talarm"
  state_topic: "shellies/shelly25-tapp_camera/overtemperature"
  qos: 0

# Shelly 2.5 tapparella Tommy
- platform: mqtt
  name: "tommy_cover_P"
  state_topic: "shellies/shelly25-tapp_Tommaso/roller/0/power"
  qos: 0
  unit_of_measurement: "W"
- platform: mqtt
  name: "tommy_cover_E"
  state_topic: "shellies/shelly25-tapp_Tommaso/roller/0/energy"
  qos: 0
  unit_of_measurement: "Wh"
  value_template: "{{ (value|float / 60) | round(2) }}" # Fix for Watt-minutes
- platform: mqtt
  name: "tommy_cover_T"
  state_topic: "shellies/shelly25-tapp_Tommaso/temperature"
  qos: 0
  unit_of_measurement: "°C"
- platform: mqtt
  name: "tommy_cover_Talarm"
  state_topic: "shellies/shelly25-tapp_Tommaso/overtemperature"
  qos: 0

# Shelly 2.5 tapparella studio
- platform: mqtt
  name: "study_cover_P"
  state_topic: "shellies/shelly25-tapp_studio/roller/0/power"
  qos: 0
  unit_of_measurement: "W"
- platform: mqtt
  name: "study_cover_E"
  state_topic: "shellies/shelly25-tapp_studio/roller/0/energy"
  qos: 0
  unit_of_measurement: "Wh"
  value_template: "{{ (value|float / 60) | round(2) }}" # Fix for Watt-minutes
- platform: mqtt
  name: "study_cover_T"
  state_topic: "shellies/shelly25-tapp_studio/temperature"
  qos: 0
  unit_of_measurement: "°C"
- platform: mqtt
  name: "study_cover_Talarm"
  state_topic: "shellies/shelly25-tapp_studio/overtemperature"
  qos: 0

# Shelly 2.5 tapparella bagnetto
- platform: mqtt
  name: "bathroom_cover_P"
  state_topic: "shellies/shelly25-tapp_bagnetto/roller/0/power"
  qos: 0
  unit_of_measurement: "W"
- platform: mqtt
  name: "bathroom_cover_E"
  state_topic: "shellies/shelly25-tapp_bagnetto/roller/0/energy"
  qos: 0
  unit_of_measurement: "Wh"
  value_template: "{{ (value|float / 60) | round(2) }}" # Fix for Watt-minutes
- platform: mqtt
  name: "bathroom_cover_T"
  state_topic: "shellies/shelly25-tapp_bagnetto/temperature"
  qos: 0
  unit_of_measurement: "°C"
- platform: mqtt
  name: "bathroom_cover_Talarm"
  state_topic: "shellies/shelly25-tapp_bagnetto/overtemperature"
  qos: 0

# Shelly H&T 1
- platform: mqtt
  name: "ht_1_T"
  state_topic: "shellies/shellyht-9551AE/sensor/temperature"
  value_template: "{{ value }}"
  unit_of_measurement: "°C"
  icon: mdi:thermometer
- platform: mqtt
  name: "ht_1_H"
  state_topic: "shellies/shellyht-9551AE/sensor/humidity"
  value_template: "{{ value }}"
  unit_of_measurement: "%"
  icon: mdi:water-percent
- platform: mqtt
  name: "ht_1_battery"
  state_topic: "shellies/shellyht-9551AE/sensor/battery"
  value_template: "{{ value }}"
  unit_of_measurement: "%"
  icon: mdi:battery

# Shelly H&T 2
- platform: mqtt
  name: "ht_2_T"
  state_topic: "shellies/shellyht-9554BF/sensor/temperature"
  value_template: "{{ value }}"
  unit_of_measurement: "°C"
  icon: mdi:thermometer
- platform: mqtt
  name: "ht_2_H"
  state_topic: "shellies/shellyht-9554BF/sensor/humidity"
  value_template: "{{ value }}"
  unit_of_measurement: "%"
  icon: mdi:water-percent
- platform: mqtt
  name: "ht_2_battery"
  state_topic: "shellies/shellyht-9554BF/sensor/battery"
  value_template: "{{ value }}"
  unit_of_measurement: "%"
  icon: mdi:battery
