# Shelly 1PM ingresso
- platform: mqtt
  name: "Luce ingresso P"
  state_topic: "shellies/shelly1pm-ingresso/relay/0/power"
  qos: 0
  unit_of_measurement: "W"
- platform: mqtt
  name: "Luce ingresso E"
  state_topic: "shellies/shelly1pm-ingresso/relay/0/energy"
  qos: 0
  unit_of_measurement: "Wh"
  value_template: "{{ (value|float / 60) | round(2) }}" # Fix for Watt-minutes
- platform: mqtt
  name: "shelly1pm ingresso T"
  state_topic: "shellies/shelly1pm-ingresso/temperature"
  qos: 0
  unit_of_measurement: "°C"
- platform: mqtt
  name: "shelly1pm ingresso Talarm"
  state_topic: "shellies/shelly1pm-ingresso/overtemperature"
  qos: 0

# Shelly 2.5 luci sala
- platform: mqtt
  name: "Flos Aim P"
  state_topic: "shellies/shelly25-luci_sala/relay/0/power"
  qos: 0
  unit_of_measurement: "W"
- platform: mqtt
  name: "Flos Aim E"
  state_topic: "shellies/shelly25-luci_sala/relay/0/energy"
  qos: 0
  unit_of_measurement: "Wh"
  value_template: "{{ (value|float / 60) | round(2) }}" # Fix for Watt-minutes
- platform: mqtt
  name: "Led divano P"
  state_topic: "shellies/shelly25-luci_sala/relay/1/power"
  qos: 0
  unit_of_measurement: "W"
- platform: mqtt
  name: "Led divano E"
  state_topic: "shellies/shelly25-luci_sala/relay/1/energy"
  qos: 0
  unit_of_measurement: "Wh"
  value_template: "{{ (value|float / 60) | round(2) }}" # Fix for Watt-minutes
- platform: mqtt
  name: "shelly25 luci sala T"
  state_topic: "shellies/shelly25-luci_sala/temperature"
  qos: 0
  unit_of_measurement: "°C"
- platform: mqtt
  name: "shelly25 luci sala Talarm"
  state_topic: "shellies/shelly25-luci_sala/overtemperature"
  qos: 0

# Shelly 2.5 led cucina
# Il relay 0 non viene monitorato perché è usato come un pulsante
- platform: mqtt
  name: "Led cucina P"
  state_topic: "shellies/shelly25-luci_cucina/relay/1/power"
  qos: 0
  unit_of_measurement: "W"
- platform: mqtt
  name: "Led cucina E"
  state_topic: "shellies/shelly25-luci_cucina/relay/1/energy"
  qos: 0
  unit_of_measurement: "Wh"
  value_template: "{{ (value|float / 60) | round(2) }}" # Fix for Watt-minutes
- platform: mqtt
  name: "shelly25 led cucina T"
  state_topic: "shellies/shelly25-luci_cucina/temperature"
  qos: 0
  unit_of_measurement: "°C"
- platform: mqtt
  name: "shelly25 led cucina Talarm"
  state_topic: "shellies/shelly25-luci_cucina/overtemperature"
  qos: 0

# Shelly 2.5 tapparella cucina
- platform: mqtt
  name: "Tapparella cucina P"
  state_topic: "shellies/shelly25-tapp_cucina/roller/0/power"
  qos: 0
  unit_of_measurement: "W"
- platform: mqtt
  name: "Tapparella cucina E"
  state_topic: "shellies/shelly25-tapp_cucina/roller/0/energy"
  qos: 0
  unit_of_measurement: "Wh"
  value_template: "{{ (value|float / 60) | round(2) }}" # Fix for Watt-minutes
- platform: mqtt
  name: "shelly25 tapparella cucina T"
  state_topic: "shellies/shelly25-tapp_cucina/temperature"
  qos: 0
  unit_of_measurement: "°C"
- platform: mqtt
  name: "shelly25 tapparella cucina Talarm"
  state_topic: "shellies/shelly25-tapp_cucina/overtemperature"
  qos: 0

# Shelly 2.5 tapparella sala balcone
- platform: mqtt
  name: "Tapparella sala balcone P"
  state_topic: "shellies/shelly25-tapp_sala_big/roller/0/power"
  qos: 0
  unit_of_measurement: "W"
- platform: mqtt
  name: "Tapparella sala balcone E"
  state_topic: "shellies/shelly25-tapp_sala_big/roller/0/energy"
  qos: 0
  unit_of_measurement: "Wh"
  value_template: "{{ (value|float / 60) | round(2) }}" # Fix for Watt-minutes
- platform: mqtt
  name: "shelly25 tapparella sala balcone T"
  state_topic: "shellies/shelly25-tapp_sala_big/temperature"
  qos: 0
  unit_of_measurement: "°C"
- platform: mqtt
  name: "shelly25 tapparella sala balcone Talarm"
  state_topic: "shellies/shelly25-tapp_sala_big/overtemperature"
  qos: 0

# Shelly 2.5 tapparella sala finestra
- platform: mqtt
  name: "Tapparella sala finestra P"
  state_topic: "shellies/shelly25-tapp_sala_small/roller/0/power"
  qos: 0
  unit_of_measurement: "W"
- platform: mqtt
  name: "Tapparella sala finestra E"
  state_topic: "shellies/shelly25-tapp_sala_small/roller/0/energy"
  qos: 0
  unit_of_measurement: "Wh"
  value_template: "{{ (value|float / 60) | round(2) }}" # Fix for Watt-minutes
- platform: mqtt
  name: "shelly25 tapparella sala finestra T"
  state_topic: "shellies/shelly25-tapp_sala_small/temperature"
  qos: 0
  unit_of_measurement: "°C"
- platform: mqtt
  name: "shelly25 tapparella sala finestra Talarm"
  state_topic: "shellies/shelly25-tapp_sala_small/overtemperature"
  qos: 0
