- platform: template
  sensors:
    led_cucina_target_power:
      entity_id: input_number.led_cucina_brightness
      value_template: "{{ states('input_number.led_cucina_min_power')|float + states('input_number.led_cucina_brightness')|float * (states('input_number.led_cucina_max_power')|float - states('input_number.led_cucina_min_power')|float) / 100 }}"

- platform: template
  sensors:
    mel_big_energy:
      unit_of_measurement: "kWh"
      value_template: "{{ ((states('sensor.hvac_living_energy') | float) + (states('sensor.hvac_bedroom_energy') | float)) | round(1) }}"
    mel_small_energy:
      unit_of_measurement: "kWh"
      value_template: "{{ ((states('sensor.hvac_study_energy') | float) + (states('sensor.hvac_tommy_energy') | float)) | round(1) }}"

- platform: template
  sensors:
    living_small_cover_position:
      value_template: "{{ state_attr('cover.living_small', 'current_position') }}"
    living_big_cover_position:
      value_template: "{{ state_attr('cover.living_big', 'current_position') }}"
    kitchen_cover_position:
      value_template: "{{ state_attr('cover.kitchen', 'current_position') }}"
    bedroom_cover_position:
      value_template: "{{ state_attr('cover.bedroom', 'current_position') }}"
    study_cover_position:
      value_template: "{{ state_attr('cover.study', 'current_position') }}"
    tommy_cover_position:
      value_template: "{{ state_attr('cover.tommy', 'current_position') }}"
