- platform: template
  sensors:
    led_cucina_target_power:
      entity_id: input_number.led_cucina_brightness
      value_template: "{{ states('input_number.led_cucina_min_power')|float + states('input_number.led_cucina_brightness')|float * (states('input_number.led_cucina_max_power')|float - states('input_number.led_cucina_min_power')|float) / 100 }}"
    avv_cucina_pos:
      entity_id: cover.cucina
      value_template: "{{ state_attr('cover.cucina', 'current_position')|int }}"
