- alias: 'Horizontal Vane Set - Sala'
  trigger:
    - platform: state
      entity_id: input_select.hvac_living_hvane
  action:
    - service: melcloud.set_vane_horizontal
      data:
        entity_id: climate.hvac_living
        position: '{{ states("input_select.hvac_living_hvane") }}'

- alias: 'Horizontal Vane Set - Camera'
  trigger:
    - platform: state
      entity_id: input_select.hvac_bedroom_hvane
  action:
    - service: melcloud.set_vane_horizontal
      data:
        entity_id: climate.hvac_bedroom
        position: '{{ states("input_select.hvac_bedroom_hvane") }}'

- alias: 'Horizontal Vane Set - Camera Tommaso'
  trigger:
    - platform: state
      entity_id: input_select.hvac_tommy_hvane
  action:
    - service: melcloud.set_vane_horizontal
      data:
        entity_id: climate.hvac_tommy
        position: '{{ states("input_select.hvac_tommy_hvane") }}'

- alias: 'Horizontal Vane Set - Studio'
  trigger:
    - platform: state
      entity_id: input_select.hvac_study_hvane
  action:
    - service: melcloud.set_vane_horizontal
      data:
        entity_id: climate.hvac_study
        position: '{{ states("input_select.hvac_study_hvane") }}'

- alias: 'Horizontal Vane Get - Sala'
  trigger:
    - platform: state
      entity_id: climate.hvac_living
      attribute: vane_horizontal
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.hvac_living_hvane
        option: '{{state_attr("climate.hvac_living", "vane_horizontal") }}'

- alias: 'Horizontal Vane Get - Camera'
  trigger:
    - platform: state
      entity_id: climate.hvac_bedroom
      attribute: vane_horizontal
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.hvac_bedroom_hvane
        option: '{{state_attr("climate.hvac_bedroom", "vane_horizontal") }}'

- alias: 'Horizontal Vane Get - Camera Tommaso'
  trigger:
    - platform: state
      entity_id: climate.hvac_tommy
      attribute: vane_horizontal
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.hvac_tommy_hvane
        option: '{{state_attr("climate.hvac_tommy", "vane_horizontal") }}'

- alias: 'Horizontal Vane Get - Studio'
  trigger:
    - platform: state
      entity_id: climate.hvac_study
      attribute: vane_horizontal
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.hvac_study_hvane
        option: '{{state_attr("climate.hvac_study", "vane_horizontal") }}'

