- alias: "Shelly i3 cucina"
  trigger:
    platform: mqtt
    topic: "shellies/shellyi3-cucina/input_event/0"
  condition:
    - condition: template
      value_template: "{{ trigger.payload_json.event == 'S' or trigger.payload_json.event == 'SS' or trigger.payload_json.event == 'L' }}"
  action:
  - service: logbook.log
    data:
      name: automation Sheylly i3 cucina
      message: "Payload is {{ trigger.payload_json.event }}, count = {{ trigger.payload_json.event_cnt }}"
  - service_template: >
      {% if trigger.payload_json.event == "L" %}
        script.turn_on
      {% else %}
        light.toggle
      {% endif %}
    data_template:
      entity_id: >
        {% if trigger.payload_json.event == "S" %}
          light.led_pensili
        {% elif trigger.payload_json.event == "SS" %}
          light.ingresso
        {% else %}
          {% if states('group.luci_cucina') == 'on' %}
            script.living
          {% else %}
            script.kitchen
          {% endif %}
        {% endif %}

