- alias: "Shelly i3 cucina"
  trigger:
    platform: mqtt
    topic: "shellies/shellyi3-cucina/input_event/0"
  condition:
    - condition: template
      value_template: "{{ trigger.payload_json.event == 'S' or trigger.payload_json.event == 'SS' or trigger.payload_json.event == 'L' }}"
  action:
  - service_template: >
      {% if trigger.payload_json.event == "L" %}
        {% if states('group.luci_cucina') == 'on' %}
          homeassistant.turn_off
        {% else %}
          homeassistant.turn_on
        {% endif %}
      {% else %}
        light.toggle
      {% endif %}
    data_template:
      entity_id: >
        {% if trigger.payload_json.event == "S" %}
          light.led_pensili
        {% elif trigger.payload_json.event == "SS" %}
          light.ingresso
        {% else %}
          group.luci_cucina
        {% endif %}

