- alias: 'Git warning'
  trigger:
    - platform: state
      entity_id: sensor.git_alarm
      to: 'on'
  action:
    - service: persistent_notification.create
      data:
        title: Git warning
        message: Check git status
        notification_id: git_status

- alias: 'Git ok'
  trigger:
    - platform: state
      entity_id: sensor.git_alarm
      to: 'off'
  action:
    - service: persistent_notification.dismiss
      data:
        notification_id: git_status

- alias: 'On Home Assistant start'
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: mysql_list.get_data
    - delay: 00:05  # Waits 5 minutes
    - service: homekit.start

#- alias: "Let's Encrypt Renewal"
#  trigger:
#    platform: time
#    at: '01:25:00'
#  action:
#    - service: hassio.addon_restart
#      data:
#        addon: core_letsencrypt
